### ISSUE TITLE
Reaction file crashes MUGAST analysis

### ISSUE THREAD

**Issue by Munken** [adrien-matta/nptool#17]
```
npsimulation -D MUGAST_Agata.detector -E 15O6Li_d19Ne.reaction
```

and then 

```
npanalysis --last-sim
```

crashes with this

[15O6Li_d19Ne.txt](https://github.com/adrien-matta/nptool/files/624294/15O6Li_d19Ne.txt)

**Comment by adrien-matta** [comment]
The problem has been identified, I need to switch MUST2 to the new type of scorer. Should be solved this week.

**Comment by adrien-matta** [comment]
Update: Did not find time this week, so carry on for next week.

**Comment by adrien-matta** [comment]
Hi,
The issue has been solved. It requiered a redesigned of the MUST2 scorer handling. I also added the Interstrip effect in MUST2 as a result of switching to a better silicon scorer. Here is the corrected input file, since the read input has changed since the time the issue was open.

Thanks for your patience.
[15O6Li_d19Ne.txt](https://github.com/adrien-matta/nptool/files/749967/15O6Li_d19Ne.txt)
