### ISSUE TITLE
Randomizing channels prior to calibration 

### ISSUE THREAD

**Issue by moukaddam** [adrien-matta/nptool#26]
@adrien-matta I was wondering why raw data values are not systematically randomised prior to calibration.
is there any good reason for that?

**Comment by adrien-matta** [comment]
You suggest to add a random number between 0 and 1 prior to applying the calibration? Is that standard practice, never heard of it, but look sensible to me.

I wonder if there is no special case where this should not be down. At the very list, we should add a flag to turn the switch off if needed with a default value to true in the ApplyCalibration method.

**Comment by moukaddam** [comment]
That's because we are not used to high stats maybe :)
Here's an example, I used the same binning. Blue is randomized (Eraw+Random->rndm()-0.5)
![ge_randvsnot_zoom](https://cloud.githubusercontent.com/assets/5272621/23407190/ad0cea56-fdba-11e6-82b4-592d5f359566.png)

**Comment by adrien-matta** [comment]
This is not correct. You are definitely not allowed to randomize across channel, this contrary to the way the ADC works. You should add a random number from [0;1[ intervall, not from ]-0.5;0.5;[

The structure you see has nothing to do with stat, you are just using a binning that is not a multiple of the ADC range, hence the odd/even pattern. You smooth it out with the random procedure, but because you use incorrect methodology you shift the peak by half a channel (this is especially visible on in the first and third doublet).

**Comment by moukaddam** [comment]
We can in principle add a public function in the CalibrationManager singleton, that can be accessed from the Analysis.cxx, this way the user can turn it ON and OFF easily

**Comment by adrien-matta** [comment]
I just had a thoughtful discussion about this method with colleague. The 
conclusion is that it is incorrect to do so, because you cannot guaranty 
that the statistical error of the bin is still valid. You are binning 
twice data (once with the adc, and once with histogram). The only valid 
way is to choose a binning that match the adc (or any multiple).

_________________________________
*Dr Adrien Matta*
Chargé de Recherche CNRS
Groupe Structure Nucléaire
LPC Caen, ENSICAEN
6, Bd du Marechal Juin
14050 CAEN Cedex
France

**Comment by padsley** [comment]
For what it's worth, I agree with this last statement, and to me it seems like the most sensible when one thinks about what a histogram actually is (a frequency distribution, really - height*width of the bin = total number of events). Then when you have the data from the digitiser, you have the frequency of counts within a particular digitiser 'bin'. In most cases it should make very little difference to the overall result but in cases with low statistics where log-likelihood is required, then it might be important.

However, I'd also note that while I think that this is true for cases where the variable is a digitiser output, for something like angles or strip positions etc, then maybe a shift of this form might be required. I'm not sure.

td;dr: I agree no variation like this for digitiser outputs, but potentially useful for indirect derived quantities.

**Comment by shuyaota** [comment]
Randomizing ADC raw values between (0 to 1) is a familiar process to me at least. Many groups I worked with used it. I think this randomizing is nothing to do with statistical error, because we're just decoding the events in a bin to original values (e.g., if energy of the event is 100.3, it was binned by ADC to 100 (though this may be depending on ADC digitizer), so assuming, based on this ADC vale (100), the original energy is something between 100 and 101 seems to make sense to me (using a uniform distribution may provoke discussion though)). 

If we don't use this process, the calibrated energy has a pattern of only 4096 (or the number of ADC channels), which leads to a strange histogram and fitting it sounds unnatural to me (I'm not sure binning solves this strangeness, because, after all, the values in a ADC bin have exactly same energy due to no randomization). 

The point is probably, which is more profitable. If we randomize, it gains some extra uncertainties by assuming a uniform distribution (which is strictly incorrect) and assuming an ADC digitizer's conversion mechanism (e.g., linearity between 0 and 1 ch), but we get a more natural spectrum. If we don't randomise, the spectrum is simply strange, but experimentally more true to data (not sure if it is more accurate than the randomized one, which depends on how randomization gets closer to original values).

**Comment by moukaddam** [comment]
![ge_randvsnot_1_zoom](https://cloud.githubusercontent.com/assets/5272621/23412040/33402852-fdcc-11e6-9dc2-c4b9a61e83d8.png)
![ge_randvsnot_1](https://cloud.githubusercontent.com/assets/5272621/23412038/326ea20a-fdcc-11e6-8b40-ff518696f8c9.png)

I did actually start at the beginning with [0,1[ for the same reason you mention above and I agree on this point. When I ploted that (green curve) I noticed a systematic shift on the high-stat low energy peaks (see the zoomed one). This was solved with the adding of the different random window [-0.5;0.5[ but as you have noticed, only locally.

From a practical point of view, you need to know what is xlow and xhigh that corresponds to the first bin and the last bin, say for the 4096 bins in the ADC in this case, in order to plot physical spectra without staggering. These will also change for the different gains when you sum up all the segments of the detector. So it's not practical at all. At least from data representation point of vue.

I think the main point here is to whether implement the randomization ( with [0;+1[ ) or not and for applications where you need the specefic error adc-bin by adc-bin the user can choose not too.

**Comment by adrien-matta** [comment]
Hi Shuya,

What you have to understand is that you binned twice your data, and 
randomizing it is just hidding the issue, not solving it. You should not 
binned twice the data, period.

Step 1 : You measure something with an ADC having, let say 1024 channel 
-> You effectively make an  histogram

Step2: You take those binned data, and put them in an histogram with 
1000 channel -> This cause the odd/even pattern. At this point you 
should declare your histogram with 1024, that is the correct way to do it!

Randomizing it, truly let you obtain an histogram that look the same as 
the original, but you still have to demonstrate that the statistical 
error of the new bin is still sqrt(n), that is by no mean guaranty, 
since you don't know the underlaying true distribution before the first 
binning operation performed by the ADC.

My guess is that this mostly insignificant, in most cases, especially 
with large stat, but it remain an incorrect practice unless demonstrated 
otherwise (maybe the proof exist). I would still not put it in a data 
analyis tool, which implicitly encourage people to use it.

_________________________________
*Dr Adrien Matta*
Chargé de Recherche CNRS
Groupe Structure Nucléaire
LPC Caen, ENSICAEN
6, Bd du Marechal Juin
14050 CAEN Cedex
France

**Comment by shuyaota** [comment]
Hi Adrien, 

I understand your point. I'm not saying I want you to put this in NPtool. I leave it to you and Momo. Just I want to write some advantages of randomization. 

Randomization is not necessarily a negative process, because (not only makes look natural) it makes fitting easier (or less uncertain in some cases). For instance, you wrote an example, binning a data from 1024 ch ADC by 1000 ch, whereby you're losing resolution (in some cases, energy resolution is a critical issue). It doesn't cause a big problem if you can get a good histogram by 1000 ch binning, but I guess the reality is we need more rough binning (e.g, 500 ch or 250 ch) because you have only 1024 different energies. That may get unnecessarily large errors in fitting. 

But again, you're right. We didn't really demonstrate the statistical error caused by randomization, whether it's negligible or not. Or maybe assuming Gaussian distribution instead of uniform distribution gets closer to true ones if we use Gassian fitting for the histogram. But anyway, I got your point. I leave the decision to you guys.

**Comment by moukaddam** [comment]
@adrien-matta I think what you are saying is true if you are dealing with one ADC. However, I don't think there's any practical way to plot the "physics" histogram with the "right" ADC binning while conserving the property you mentioned above. Unless you calculate explicitly xlow and xhigh for bin 1 and bin 4096, where xlow and xhigh will be different for different segments of the same detector. 

So effectively, everytime you are showing physics data you are binning twice. And most of the time we have different ADCs added up together (after calibration), so it goes without saying that the original binning will not be conserved. Of course the problem becomes more obvious when you have low stat...

**Comment by adrien-matta** [comment]
Hi,

I come back to this issue after giving it  more though. I hear what you say when summing histogram that ultimately have different gain. Within that scope I guess it could make sense to randomize the data again.

**Comment by moukaddam** [comment]
Salut, 
I have added a configuration file to tune the GeTamu class to the users needs. A variable "ADC_RANDOM_BIN" toggles the random effect. By default it is not set, to make sure the user knows what is he doing.
