### ISSUE TITLE
Analysis of Simulated root file

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#28]
The root file, generated after simulation, has such a structure that its leaves (the parameters holding the data) cannot be accessed through the “Tree Viewer”of ROOT. Since I am new to both ROOT and C++, so building a macro totally on my own in a short time seems a difficult task. It would be very helpful if I could get the guidance for building a general macro for analysis.
	However, if the tree structure could be controlled and formed in a way to make the leaves accessible in Tree Viewer, that would also be a great help.

**Comment by gchristian321** [comment]
I don't know if your questions have been addressed or not, so I'll try to
make some comments that might help.

First, you can use the TBrowser to see the branches of the tree
graphically, instead of TTreeViewer:

     TBrowser* b = new TBrowser ();

This starts a graphical window, where you can click on the file, then tree
that you want to view.

I think the reason TTreeViewer doesn't work like you'd expect has to do
with the default split level of the branches​ in nptool, I'm not sure if
this can be changed or not.

In general, to construct an analysis macro, you need to create a pointer to
an instance of the class nptool uses to store your event data in the TTree,
then use TTree::GetEntry() to read back the saved data into the class. For
example, for the TIARA project I might do something like:

TTiaraHyball * Hyball = 0;
T40Tree->SetBranchAddress("TiaraHyball", & Hyball);
for( Long64_t i =0; i < T40Tree->GetEntries(); ++i) {
    T40Tree->GetEntry (i); //reads data from event i into the Hyball class
instance
    double x = Hyball->GetSomeValueX(); // use member functions of
TTiaraHyball class to extract data for analysis
    // etc...
}


Cheers,
Greg

**Comment by adrien-matta** [comment]
HI,

Sorry it took me a while to respond, I was on the plane. Greg is totally right, although I would add that in my experience the TreeViewer is more affected by the fact we use std::vector that the split level (it was at least my understanding at the time I experimented with this).

In addition to the TBrowser which works well, one can also use the Draw command to make simple macro. Something like this would plot the Energy vs Strip number bidim for detector 1 (MUST2):
SimulatedTree->Draw("fMM_StripXE_Energy: fMM_StripXE_StripNbr>>h(128,1,128,1000,0,10)","fMM_StripXE_StripNbr == 1","colz")

One can then get the h histogram with:
TH1* h = (TH1*) gDirectory->FindObjectAny("h");

**Comment by mustak21** [comment]
Hi all,
Thank you for your valuable comments. I needed to ask one more thing. What I learnt from the "Examples" and "Projects" is that to perform analysis on the simulated root file I need to create the analysis.cxx,analysis.h and the ShowResults.C files. Although it seems to me that I can create the ShowResults.C file following the examples but the analysis.cxx and analysis.h files are very specific to the particular experiment one deals with. I wanted to know if there is any general template or something to create these two files? Also if there is any other way of analysing the simulated root file then please enlighten me!

**Comment by adrien-matta** [comment]
Hi,

In essence the project are designed as user send box to perform the last bit of analysis specific to there experiment. The only template are method of the analysis class called by the framework, behond that it is up to you to know what kind of observable you need. The ShowResult macro is just a way of displaying you data from the result tree, but you can use any mechanism you are confortable with.
