### ISSUE TITLE
npanalysis - selecting a portion of useful data in the output tree

### ISSUE THREAD

**Issue by moukaddam** [adrien-matta/nptool#34]
Is there a way to store only a portion of the analysed tree?  
The point is to optimise the time spent at during the preliminary analysis. 

In the npanalysis.cxx the portion where we fill the tree follows the 'Building of a physical event" without any check from the user:

`for (unsigned int i = 0 ; i < nentries; i++) { 
        // Get the raw Data
        Chain -> GetEntry(i);
        // Build the current event
        myDetector->BuildPhysicalEvent();
        // Fill the tree
        tree->Fill();
etc...
} `

One way to do what is suggested is to redefine BuildPhysicalEvent() with a return value, that can be used as a condition to Fill the tree or to skip this step.

(Cc @ryanwilkinson)

**Comment by adrien-matta** [comment]
I see why one want to do this but the nature of the return value is inherently different for each experiement. How would you deal with that?

Also another concern, is that if the output tree is not the same size and same order of the input tree, then you can no longer friend the tree, which is a very usefull feature.

I can add something similar to the TSelector, that the user can code, and depending on the return value, he analysis of the event is done or not. 

I however doubt the costly operation are done in the analysis, they should be done in the detector classes, which you have to go through in order to apply your filter.

The wrokflow that I think works best, is to run just the build physical events, and then re run only the analysis using the Physical tree as an input.

To do that you suppress the libNPAnalysis.so and run npanalysis, it will only produce the Physical tree, with out user analysis. Then run the analysis using the --IP flag to not do the Build again:
> rm libNPAnalysis.so
> npanalysis -D ...
> make
> npanalysis --IP -D ...

**Comment by padsley** [comment]
I don't know if "portion" means just a part or just the useful bits but if the latter, you can use TTree::CopyTree with a selection to make a TTree filtered on "good" events and then use that as an input to the analyser.

I (read: I told my student to) do this with K600 data from iThemba - I know that I'm only interested in tritons at the focal plane so you can use this function to gate only on them and reject everything else, which isn't of interest anyway. This means that the size of the TTrees that I actually analyse are reduced in size by around 90% (removing the tons of deuterons and protons).

I don't know if that's a useful suggestion but I figured I might as welll pass it along.
