### ISSUE TITLE
Segmentation violation error while doing simulation.

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#37]
Hi,
While doing the simulation of 7Be(d,t)6Be->alpha+p+p I am facing the following errors. I am attaching the input reaction file as well as the error file. Please have a look.

[7Be(d,t) error.docx](https://github.com/adrien-matta/nptool/files/1054415/7Be.d.t.error.docx)
[7Bedt_reaction.docx](https://github.com/adrien-matta/nptool/files/1054417/7Bedt_reaction.docx)

**Comment by padsley** [comment]
Hi,

I'm wondering if this is related to the problem that I was having where the beam was sometimes not being initialised correctly. Could you try running the code again a couple of times and seeing if it works or if it fails every time? (Just trying to work out if someone else has my problem, see #25).

**Comment by mustak21** [comment]
Hi,
I ran it many times but the same fault is occurring each time !

**Comment by padsley** [comment]
OK. Then it isn't the same fault. Thanks for checking. I don't think I have your detector input file so I can't check that. Can you post that here as well?

**Comment by mustak21** [comment]
I tried running the code with any random detector already built in NPTOOL but the result is still the same.
Still I am attaching the detector file. BB7 is similar to that of W1 except that it has 32 strips instead of 16 and annular S3 is similar to that of annular S1 except of few geometry changes.I guess you can just use annular S1 and W1 in place of annularS3 and BB7 respectively or I can mail you the detector files.
[is554 detector .docx](https://github.com/adrien-matta/nptool/files/1055123/is554.detector.docx)

**Comment by padsley** [comment]
OK. Having just found a moment to run your code, I get this error:

```
//// Particle decay found for6Be
 Daughter: 4He 1H 1H 
 shoot: 1 1 1 
WARNING: Using default units for token ExcitationEnergy
 ExcitationEnergy (MeV): 0 0 0 
 DifferentialCrossSection: flat.txt 
ERROR : Missmatching information (User CS allowed only for two body decay): Getting out 

```
Why this comes up as an error for me and not for you is probably due to the versions of NPTool or something like that.

What I would suggest is that you use something like this instead (which is from my code which tries to look at 12C decay into 3 alpha particles):

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ParticleDecay 12C
  Daughter= 4He 4He 4He
  ExcitationEnergy= 0 0 0
  shoot= 1 1 1
```

It may also be worth noting that, for the purposes of your simulation, I think that 6Be is thought to have a correlated proton decay (iirc, which isn't usually the case) so simulating the behaviour of two uncorrelated protons might be misleading.

**Comment by padsley** [comment]
For clarity, I think that you can't use the cross section for a 3-body decay. You have included one:
```
ParticleDecay 6Be
  Daughter= 4He 1H 1H
  ExcitationEnergy= 0 0 0
  DifferentialCrossSection=flat.txt 
  shoot= 1 1 1
```

**Comment by mustak21** [comment]
So removing the line `DifferentialCrossSection=flat.txt ` works fine and the simulation is running fine.
As you said that the two protons in 6Be decay is correlated but NPTOOL does that in complete random manner.So this is true for any correlated decay in NPTOOL simulation ?

**Comment by mustak21** [comment]
For example if I do simulation of the reaction 7Be(d,p)8Be->alpha+alpha. So in this case also will the simulation be misleading?

**Comment by padsley** [comment]
Um. I think I may have caused confusion.

The simulation will (probably) show you how a 6Be->4He+p+p 3-body decay would look. Which is fine, because you can see how that would look. However, another decay mode (e.g. 6Be->4He+2p->p+p, i.e. a decay with a "diproton") would look different. As you don't know what the decay mode actually looks like, I'd just take the NPTool default for now. If you look at the experimental data and see something which is a bit odd, then you could try playing with how the breakup looks.

For the 8Be case, the 2 4He from the ground state come out with a clear correlation due to the low relative energy in the unbound 8Be ground state. However, in the case of 7Be(d,p)8Be, you have a 2-body decay 8Be->2*4He so it shouldn't be a problem.

Unless you object, I suggest closing this issue as the problems being discussed here aren't NPTool ones but physics ones...
