### ISSUE TITLE
Rectangular beam profile

### ISSUE THREAD

**Issue by moukaddam** [adrien-matta/nptool#45]
Salut, 
Often in _in-beam_ fragmentation experiments the beam profile looks more like a rectangular profile with  gaussian borders (see image). If we normally have the data we can use the ProfilePath option to reproduce a very realistic beam profile. However, if one wants to replecate in a simple way the profile from an image of the beam it might be useful to have a "rectangular" distribution for X an Y, this will only move the centroid of the beam within a rectangle centered at the beam position. If you think that's interesting for the collaboration I can push in my changes. The same thing could be said about the beam energy, it would be nice to have the option of uniform distribution arounf the beam energy in addition to the gaussian.
![image](https://user-images.githubusercontent.com/5272621/30969444-4ef54bd8-a45a-11e7-8e03-2412417905f9.png)

**Comment by adrien-matta** [comment]
Hi,
I feel like this is covered by the more generic case of a beam profile given via histogram or file. What is the issue is this approach in your case? Generating the input file seems easy enough. I am mainly concern by adding additional code to be maintained, while not really providing more functionality.

**Comment by moukaddam** [comment]
Salut, 
it is indeed, I actually adapted a quick macro to produce a very similar beam profile... 
I'll close this issue.
