### ISSUE TITLE
Excitation-Energy Randomisation and Event Rate dropping

### ISSUE THREAD

**Issue by padsley** [adrien-matta/nptool#50]
When I try to run NPTool using a histogram for excitation energy, I find that it tends to run very slowly, and gets slower in contrast to the very similar code for the random angle generation.

Has anyone else seen this happening with NPTOOL or another GEANT4 simulation? I'm presently running valgrind to try to work out if and when a memory leak is occurring but there's nothing obvious leaping out at me at the moment.

So... my query is: "Has anyone else seen this behaviour?" If you haven't ever tried using an Ex histogram input rather than one set value for Ex in the input file, could you try and let me know if it's got this same behaviour of the event rate dropping fairly quickly?

Thanks.

**Comment by adrien-matta** [comment]
Hi Phil,
After some digging I understood the issue where Geant4 was generating a new Ion for each of the different excitation energy. The issue is solved by the addition of a flag you can add to the two body event generator. When the flag is on, geant4 produce and track the ion in its ground state, regardless of the excitation energy used for kinematic calculation. The flag is : UseExInGeant4= 0
